
version: '2'

volumes:
  peer0.uio.hth:
  peer1.uio.hth:

services:

  ca.uio.hth:
    container_name: ca.uio.hth
    image: hyperledger/fabric-ca:1.4.0
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.uio.hth-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/750471e0f61b4e9f6693888807e2519623a2999604ffe1ed5062e6ede2bae4b7_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.uio.hth-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/750471e0f61b4e9f6693888807e2519623a2999604ffe1ed5062e6ede2bae4b7_sk
#    ports:
#      - 9054:7054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../artifacts/crypto-config/peerOrganizations/uio.hth/ca/:/etc/hyperledger/fabric-ca-server-config
      - ../artifacts/fabric-ca-server-config-uio.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml

  peer0.uio.hth:
    container_name: peer0.uio.hth
    extends:
      file: base-intercept.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.uio.hth
      - CORE_PEER_LOCALMSPID=uioMSP
      - CORE_PEER_ADDRESS=peer0.uio.hth:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.uio.hth:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.uio.hth:7051
    ports:
      - 9051:7051
      - 9053:7053
    volumes:
        - ../artifacts/crypto-config/peerOrganizations/uio.hth/peers/peer0.uio.hth/:/etc/hyperledger/crypto/peer
        - peer0.uio.hth:/var/hyperledger/production
    depends_on:
      - ca.uio.hth
    

  peer1.uio.hth:
    container_name: peer1.uio.hth
    extends:
      file: base-intercept.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.uio.hth
      - CORE_PEER_LOCALMSPID=uioMSP
      - CORE_PEER_ADDRESS=peer1.uio.hth:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.uio.hth:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.uio.hth:7051
    ports:
      - 9056:7051
      - 9058:7053
    volumes:
        - ../artifacts/crypto-config/peerOrganizations/uio.hth/peers/peer1.uio.hth/:/etc/hyperledger/crypto/peer
        - peer1.uio.hth:/var/hyperledger/production
    depends_on:
      - ca.uio.hth
    

  # fabric-rest api server
  api.uio.hth:
    extends:
      file: base-intercept.yaml
      service: api-base
    container_name: api.uio.hth
    ports:
      - 8083:4000
    environment:
      - ORG=uio
      - PORT=4000
 #   volumes:
 #     - ../artifacts/hosts/uio/api_hosts:/etc/hosts
    depends_on:
      - peer0.uio.hth
      - peer1.uio.hth
    

  cli.hth:
    container_name: cli.hth
    extends:
      file: base-intercept.yaml
      service: cli-base
    volumes:
      - ../artifacts/crypto-config/ordererOrganizations/hth/orderers/orderer.hth/tls:/etc/hyperledger/crypto/orderer/tls

  cli.uio.hth:
    container_name: cli.uio.hth
    extends:
      service: cli.hth
    environment:
      - CORE_PEER_LOCALMSPID=uioMSP
    volumes:
    #    - ../artifacts/hosts/uio/cli_hosts:/etc/hosts
        - ../artifacts/crypto-config/peerOrganizations/uio.hth/users/Admin@uio.hth:/etc/hyperledger/crypto/peer
    

  cliNoCryptoVolume.uio.hth:
    container_name: cliNoCryptoVolume.uio.hth
    extends:
      file: base-intercept.yaml
      service: cli-base
    environment:
      - CORE_PEER_LOCALMSPID=uioMSP
    volumes:
        - ../artifacts/hosts/uio/cli_hosts:/etc/hosts

  www.uio.hth:
    extends:
      file: base-intercept.yaml
      service: www-base
    container_name: www.uio.hth
    ports:
      - 4002:80
    volumes:
      - ../www:/usr/share/nginx/html:ro
      - ../artifacts/nginx-uio.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api.uio.hth
