
version: '2'

volumes:
  peer0.imperial.hth:
  peer1.imperial.hth:

services:

  ca.imperial.hth:
    container_name: ca.imperial.hth
    image: hyperledger/fabric-ca:1.4.0
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.imperial.hth-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/40d1e47ee04eb0e8cc44a16c8abda62195d5a163166c9cc283e3d999a6fd8448_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.imperial.hth-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/40d1e47ee04eb0e8cc44a16c8abda62195d5a163166c9cc283e3d999a6fd8448_sk
#    ports:
#      - 7054:7054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../artifacts/crypto-config/peerOrganizations/imperial.hth/ca/:/etc/hyperledger/fabric-ca-server-config
      - ../artifacts/fabric-ca-server-config-imperial.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml

  peer0.imperial.hth:
    container_name: peer0.imperial.hth
    extends:
      file: base-intercept.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.imperial.hth
      - CORE_PEER_LOCALMSPID=imperialMSP
      - CORE_PEER_ADDRESS=peer0.imperial.hth:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.imperial.hth:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.imperial.hth:7051
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - ../artifacts/crypto-config/peerOrganizations/imperial.hth/peers/peer0.imperial.hth/:/etc/hyperledger/crypto/peer
        - peer0.imperial.hth:/var/hyperledger/production
    depends_on:
      - ca.imperial.hth
    

  peer1.imperial.hth:
    container_name: peer1.imperial.hth
    extends:
      file: base-intercept.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.imperial.hth
      - CORE_PEER_LOCALMSPID=imperialMSP
      - CORE_PEER_ADDRESS=peer1.imperial.hth:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.imperial.hth:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.imperial.hth:7051
    ports:
      - 7056:7051
      - 7058:7053
    volumes:
        - ../artifacts/crypto-config/peerOrganizations/imperial.hth/peers/peer1.imperial.hth/:/etc/hyperledger/crypto/peer
        - peer1.imperial.hth:/var/hyperledger/production
    depends_on:
      - ca.imperial.hth
    

  # fabric-rest api server
  api.imperial.hth:
    extends:
      file: base-intercept.yaml
      service: api-base
    container_name: api.imperial.hth
    ports:
      - 8081:4000
    environment:
      - ORG=imperial
      - PORT=4000
 #   volumes:
 #     - ../artifacts/hosts/imperial/api_hosts:/etc/hosts
    depends_on:
      - peer0.imperial.hth
      - peer1.imperial.hth
    

  cli.hth:
    container_name: cli.hth
    extends:
      file: base-intercept.yaml
      service: cli-base
    volumes:
      - ../artifacts/crypto-config/ordererOrganizations/hth/orderers/orderer.hth/tls:/etc/hyperledger/crypto/orderer/tls

  cli.imperial.hth:
    container_name: cli.imperial.hth
    extends:
      service: cli.hth
    environment:
      - CORE_PEER_LOCALMSPID=imperialMSP
    volumes:
    #    - ../artifacts/hosts/imperial/cli_hosts:/etc/hosts
        - ../artifacts/crypto-config/peerOrganizations/imperial.hth/users/Admin@imperial.hth:/etc/hyperledger/crypto/peer
    

  cliNoCryptoVolume.imperial.hth:
    container_name: cliNoCryptoVolume.imperial.hth
    extends:
      file: base-intercept.yaml
      service: cli-base
    environment:
      - CORE_PEER_LOCALMSPID=imperialMSP
    volumes:
        - ../artifacts/hosts/imperial/cli_hosts:/etc/hosts

  www.imperial.hth:
    extends:
      file: base-intercept.yaml
      service: www-base
    container_name: www.imperial.hth
    ports:
      - 4000:80
    volumes:
      - ../www:/usr/share/nginx/html:ro
      - ../artifacts/nginx-imperial.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api.imperial.hth
